from tkinter import*
from tkinter import ttk

def test1():
    def true1():
        t1.destroy()
        test2()
    def false1():
        t1.destroy()
        wrong1()
    t1=Tk()
    t1.title('Ring of fire')
    t1.geometry('750x550')
    t1.configure(background='#FFDD8F')
    t1_F = Frame(t1, width=750, height=600)
    t1_F.configure(background='#FFDD8F')
    s = Label(t1_F, text='1.บริเวณบนผิวโลกที่เกิดแผ่นดินไหวบ่อยมากที่สุดได้แก่บริเวณใด', font=('Angsana New', 20), fg='#703400', width=75)
    s.pack()
    B = Button(t1_F, text='ก.บริเวณวงแหวนแห่งไฟ', font=('Angsana New', 20), bg="#FFC796", width=34, command=true1)
    B.pack(pady=20)
    B2 = Button(t1_F, text='ข.แนวรอยต่อภูเขาแอลป์กับภูเขาหิมาลัย', font=('Angsana New', 20), bg="#FFC796" ,width=34, command=false1)
    B2.pack(pady=20)
    B3 = Button(t1_F, text='ค.บริเวณใจกลางแผ่นยูราเซียน (Eurasian plate)', font=('Angsana New', 20), bg="#FFC796", width=34, command=false1)
    B3.pack(pady=20)
    B4 = Button(t1_F, text='ง.บริเวณเทือกเขากลางมหาสมุทรแอตแลนติก', font=('Angsana New', 20), bg="#FFC796", width=34, command=false1)
    B4.pack(pady=20)
    t1_F.pack()
    t1.mainloop()

def test2():
    def true2():
        t2.destroy()
        test3()
    def false2():
        t2.destroy()
        wrong2()
    t2 = Tk()
    t2.title('Ring of fire')
    t2.geometry('750x550')
    t2.configure(background='#FFDD8F')
    t2_F = Frame(t2, width=600, height=600)
    t2_F.configure(background='#FFDD8F')
    s = Label(t2_F, text='2.พื้นที่ในข้อใดที่เรียกว่า วงแหวนแห่งไฟ', font=('Angsana New', 20), fg='#703400',
              width=75)
    s.pack()
    B = Button(t2_F, text='ก.บริเวณรอยต่อภูเขาแอลป์ในทวีปยุโรป', font=('Angsana New', 20), bg="#FFC796", width=32, command=false2)
    B.pack(pady=20)
    B2 = Button(t2_F, text='ข.แนวรอยต่อภูเขาหิมาลัยในทวีปเอเซีย', font=('Angsana New', 20), bg="#FFC796", width=32,
                command=false2)
    B2.pack(pady=20)
    B3 = Button(t2_F, text='ค.บริเวณขอบมหาสมุทรแปซิฟิกทั้งหมด', font=('Angsana New', 20), bg="#FFC796",
                width=32, command=true2)
    B3.pack(pady=20)
    B4 = Button(t2_F, text='ง.บริเวณเทือกเขากลางมหาสมุทรแอตแลนติ', font=('Angsana New', 20), bg="#FFC796", width=32,
                command=false2)
    B4.pack(pady=20)
    t2_F.pack()
    t2.mainloop()

def test3():
    def true3():
        t2.destroy()
        test4()
    def false3():
        t2.destroy()
        wrong3()
    t2 = Tk()
    t2.title('Ring of fire')
    t2.geometry('750x550')
    t2.configure(background='#FFDD8F')
    t2_F = Frame(t2, width=600, height=600)
    t2_F.configure(background='#FFDD8F')
    s = Label(t2_F, text='3. ข้อใดไม่อยู่ในบริเวณที่เรียกว่า วงแหวนแห่งไฟ( ring of fire)', font=('Angsana New', 20), fg='#703400',
              width=75)
    s.pack()
    B = Button(t2_F, text='ก.บริเวณขอบมหาสมุทรแปซิฟิกทั้งหมด', font=('Angsana New', 20), bg="#FFC796", width=32, command=false3)
    B.pack(pady=20)
    B2 = Button(t2_F, text='ข.บริเวณรอยต่อภูเขาแอลป์และภูเขาหิมาลัย', font=('Angsana New', 20), bg="#FFC796", width=32,
                command=true3)
    B2.pack(pady=20)
    B3 = Button(t2_F, text='ค.ประเทศญี่ปุ่นทั้งหมด', font=('Angsana New', 20), bg="#FFC796",
                width=32, command=false3)
    B3.pack(pady=20)
    B4 = Button(t2_F, text='ง.บริเวณด้านตะวันตกของประเทศเม็กซิโก', font=('Angsana New', 20), bg="#FFC796", width=32,
                command=false3)
    B4.pack(pady=20)
    t2_F.pack()
    t2.mainloop()

def test4():
    def true4():
        t2.destroy()
        test5()
    def false4():
        t2.destroy()
        wrong4()
    t2 = Tk()
    t2.title('Ring of fire')
    t2.geometry('750x550')
    t2.configure(background='#FFDD8F')
    t2_F = Frame(t2, width=600, height=600)
    t2_F.configure(background='#FFDD8F')
    s = Label(t2_F, text='4.การกําเนิดของ "วงแหวนแห่งไฟ" นั้น สืบเนื่องมาจากแผ่นเปลือกโลกเคลื่อนที่มาชนกันและมุดตัวซ้อนกันในแต่ละทวีปเมื่อหลายล้านปีก่อน ยกตัวอย่าง\n'
                         ' เช่น แผ่นโคคอสในอเมริกากลาง ชนกับแผ่นอเมริกาเหนืออยากทราบว่า แผ่นนาซคา เคลื่อนที่ชนกับแผ่นทวีปใด)', font=('Angsana New', 20), fg='#703400',
              width=130)
    s.pack()
    B = Button(t2_F, text='ก.ทวีปออสเตรเลีย', font=('Angsana New', 20), bg="#FFC796", width=32, command=false4)
    B.pack(pady=20)
    B2 = Button(t2_F, text='ข.ทวีปอาเมริกาใต้', font=('Angsana New', 20), bg="#FFC796", width=32,
                command=false4)
    B2.pack(pady=20)
    B3 = Button(t2_F, text='ค.ทวีปแอฟริกา', font=('Angsana New', 20), bg="#FFC796",
                width=32, command=true4)
    B3.pack(pady=20)
    B4 = Button(t2_F, text='ง.ทวีปยุโรป', font=('Angsana New', 20), bg="#FFC796", width=32,
                command=false4)
    B4.pack(pady=20)
    t2_F.pack()
    t2.mainloop()
def test5():
    def true5():
        t2.destroy()
        test6()
    def false5():
        t2.destroy()
        wrong5()
    t2 = Tk()
    t2.title('Ring of fire')
    t2.geometry('750x550')
    t2.configure(background='#FFDD8F')
    t2_F = Frame(t2, width=600, height=600)
    t2_F.configure(background='#FFDD8F')
    s = Label(t2_F, text='5.วงแหวนแห่งไฟครอบคลุมพื้นที่ในมหาสมุทรและประเทศในทวีปต่างๆ\nรวมกันถึง 31 ประเทศ ยกเว้น ประเทศใด', font=('Angsana New', 20), fg='#703400',
              width=75)
    s.pack()
    B = Button(t2_F, text='ก.ประเทศเนเธอร์แลนด์', font=('Angsana New', 20), bg="#FFC796", width=32, command=true5)
    B.pack(pady=20)
    B2 = Button(t2_F, text='ข.ประเทศบลาซิล', font=('Angsana New', 20), bg="#FFC796", width=32,
                command=false5)
    B2.pack(pady=20)
    B3 = Button(t2_F, text='ค.ประเทศแคนนาดา', font=('Angsana New', 20), bg="#FFC796",
                width=32, command=false5)
    B3.pack(pady=20)
    B4 = Button(t2_F, text='ง.ประเทศชิลี', font=('Angsana New', 20), bg="#FFC796", width=32,
                command=false5)
    B4.pack(pady=20)
    t2_F.pack()
    t2.mainloop()
def test6():
    def true6():
        t2.destroy()
        test7()
    def false6():
        t2.destroy()
        wrong6()
    t2 = Tk()
    t2.title('Ring of fire')
    t2.geometry('750x550')
    t2.configure(background='#FFDD8F')
    t2_F = Frame(t2, width=600, height=600)
    t2_F.configure(background='#FFDD8F')
    s = Label(t2_F, text='6.รอยเลื่อนควีนชาร์ลอตต์เกิดแผ่นดินไหวขนาดใหญ่จำนวน 3 ครั้ง ในช่วงปีไหน', font=('Angsana New', 20), fg='#703400',
              width=75)
    s.pack()
    B = Button(t2_F, text='ก. ค.ศ. 1928 - 1980', font=('Angsana New', 20), bg="#FFC796", width=32, command=false6)
    B.pack(pady=20)
    B2 = Button(t2_F, text='ข. ค.ศ. 1956 - 1990', font=('Angsana New', 20), bg="#FFC796", width=32,
                command=false6)
    B2.pack(pady=20)
    B3 = Button(t2_F, text='ค. ค.ศ. 1970 - 2001', font=('Angsana New', 20), bg="#FFC796",
                width=32, command=false6)
    B3.pack(pady=20)
    B4 = Button(t2_F, text='ง. ค.ศ. 1929 – 1970', font=('Angsana New', 20), bg="#FFC796", width=32,
                command=true6)
    B4.pack(pady=20)
    t2_F.pack()
    t2.mainloop()

def test7():
    def true7():
        t2.destroy()
        test8()
    def false7():
        t2.destroy()
        wrong7()
    t2 = Tk()
    t2.title('Ring of fire')
    t2.geometry('750x550')
    t2.configure(background='#FFDD8F')
    t2_F = Frame(t2, width=600, height=600)
    t2_F.configure(background='#FFDD8F')
    s = Label(t2_F, text='7.ภูเขาไฟพินาตูโบในฟิลิปปินส์ ระเบิดครั้งรุนแรงที่สุดรุนแรงเป็นอันดับที่เท่าไหร่ในศตวรรษที่ 20', font=('Angsana New', 20), fg='#703400',
              width=75)
    s.pack()
    B = Button(t2_F, text='ก.อันดับที่ 1', font=('Angsana New', 20), bg="#FFC796", width=32, command=false7)
    B.pack(pady=20)
    B2 = Button(t2_F, text='ข.อันดับที่ 2', font=('Angsana New', 20), bg="#FFC796", width=32,
                command=true7)
    B2.pack(pady=20)
    B3 = Button(t2_F, text='ค.อันดับที่ 3', font=('Angsana New', 20), bg="#FFC796",
                width=32, command=false7)
    B3.pack(pady=20)
    B4 = Button(t2_F, text='ง.อันดับที่ 4', font=('Angsana New', 20), bg="#FFC796", width=32,
                command=false7)
    B4.pack(pady=20)
    t2_F.pack()
    t2.mainloop()
def test8():
    def true8():
        t2.destroy()
        answer()
    def false8():
        t2.destroy()
        wrong8()
    t2 = Tk()
    t2.title('Ring of fire')
    t2.geometry('750x650')
    t2.configure(background='#FFDD8F')
    t2_F = Frame(t2, width=600, height=600)
    t2_F.configure(background='#FFDD8F')
    s = Label(t2_F, text='8.ภูเขาไฟที่ยังคุกรุ่นและการเกิดแผ่นดินไหวในวงแหวนแห่งไฟดังภาพ  มีชื่อว่าอะไร', font=('Angsana New', 20), fg='#703400',
              width=75)
    s.pack()
    r = PhotoImage(file="ภูเขาไฟแทมโบลา.png")
    d = Label(t2_F, image=r)
    d.pack()
    B = Button(t2_F, text='ก.ภูเขาไฟแทมโบรา', font=('Angsana New', 20), bg="#FFC796", width=32, command=true8)
    B.pack(pady=20)
    B2 = Button(t2_F, text='ข.ภูเขาไฟฟูจิ', font=('Angsana New', 20), bg="#FFC796", width=32,
                command=false8)
    B2.pack(pady=20)
    B3 = Button(t2_F, text='ค.ภูเขาไฟพินาตูโบ', font=('Angsana New', 20), bg="#FFC796",
                width=32, command=false8)
    B3.pack(pady=20)
    B4 = Button(t2_F, text='ง.ภูเขาไฟลูอาเปทู', font=('Angsana New', 20), bg="#FFC796", width=32,
                command=false8)
    B4.pack(pady=20)
    t2_F.pack()
    t2.mainloop()
def wrong1():
    def try1():
        w1.destroy()
        test1()
    def next1():
        w1.destroy()
        test2()
    w1 = Tk()
    w1.title('Ring of fire')
    w1.geometry('750x650')
    w1.configure(background='red')
    w1_F = Frame(w1, width=600, height=600)
    w1_F.configure(background='red')
    Ring_Lb = Label(w1_F, text='ดูเหมือนว่าคุณจะตอบผิดนะ ลองใหม่อีกครั้งหรือไม่', font=('Angsana New', 30),bg='pink', width=50,height=2)
    Ring_Lb.pack()
    r = PhotoImage(file="w1.png")
    d = Label(w1_F, image=r)
    d.pack()
    B = Button(w1_F, text='Try again', font=('Angsana New', 25), bg="#FFC796", command=try1)
    B.pack(pady=20)
    B2 = Button(w1_F, text='Next', font=('Angsana New', 25), bg="#FFC796", command=next1)
    B2.pack(pady=20)
    w1_F.pack()
    w1.mainloop()
def wrong2():
    def try2():
        w2.destroy()
        test2()
    def next2():
        w2.destroy()
        test3()
    w2 = Tk()
    w2.title('Ring of fire')
    w2.geometry('750x650')
    w2.configure(background='red')
    w2_F = Frame(w2, width=600, height=600)
    w2_F.configure(background='red')
    Ring_Lb = Label(w2_F, text='ดูเหมือนว่าคุณจะตอบผิดนะ ลองใหม่อีกครั้งหรือไม่', font=('Angsana New', 30),bg='pink', width=50,height=2)
    Ring_Lb.pack()
    r = PhotoImage(file="w1.png")
    d = Label(w2_F, image=r)
    d.pack()
    B = Button(w2_F, text='Try again', font=('Angsana New', 25), bg="#FFC796", command=try2)
    B.pack(pady=20)
    B2 = Button(w2_F, text='Next', font=('Angsana New', 25), bg="#FFC796", command=next2)
    B2.pack(pady=20)
    w2_F.pack()
    w2.mainloop()
def wrong3():
    def try3():
        w3.destroy()
        test3()
    def next3():
        w3.destroy()
        test4()
    w3 = Tk()
    w3.title('Ring of fire')
    w3.geometry('750x650')
    w3.configure(background='red')
    w3_F = Frame(w3, width=600, height=600)
    w3_F.configure(background='red')
    Ring_Lb = Label(w3_F, text='ดูเหมือนว่าคุณจะตอบผิดนะ ลองใหม่อีกครั้งหรือไม่', font=('Angsana New', 30),bg='pink', width=50,height=2)
    Ring_Lb.pack()
    r = PhotoImage(file="w1.png")
    d = Label(w3_F, image=r)
    d.pack()
    B = Button(w3_F, text='Try again', font=('Angsana New', 25), bg="#FFC796", command=try3)
    B.pack(pady=20)
    B2 = Button(w3_F, text='Next', font=('Angsana New', 25), bg="#FFC796", command=next3)
    B2.pack(pady=20)
    w3_F.pack()
    w3.mainloop()
def wrong4():
    def try4():
        w4.destroy()
        test4()
    def next4():
        w4.destroy()
        test5()
    w4 = Tk()
    w4.title('Ring of fire')
    w4.geometry('750x650')
    w4.configure(background='red')
    w4_F = Frame(w4, width=600, height=600)
    w4_F.configure(background='red')
    Ring_Lb = Label(w4_F, text='ดูเหมือนว่าคุณจะตอบผิดนะ ลองใหม่อีกครั้งหรือไม่', font=('Angsana New', 30),bg='pink', width=50,height=2)
    Ring_Lb.pack()
    r = PhotoImage(file="w1.png")
    d = Label(w4_F, image=r)
    d.pack()
    B = Button(w4_F, text='Try again', font=('Angsana New', 25), bg="#FFC796", command=try4)
    B.pack(pady=20)
    B2 = Button(w4_F, text='Next', font=('Angsana New', 25), bg="#FFC796", command=next4)
    B2.pack(pady=20)
    w4_F.pack()
    w4.mainloop()
def wrong5():
    def try5():
        w5.destroy()
        test5()
    def next5():
        w5.destroy()
        test6()
    w5 = Tk()
    w5.title('Ring of fire')
    w5.geometry('750x650')
    w5.configure(background='red')
    w5_F = Frame(w5, width=600, height=600)
    w5_F.configure(background='red')
    Ring_Lb = Label(w5_F, text='ดูเหมือนว่าคุณจะตอบผิดนะ ลองใหม่อีกครั้งหรือไม่', font=('Angsana New', 30),bg='pink', width=50,height=2)
    Ring_Lb.pack()
    r = PhotoImage(file="w1.png")
    d = Label(w5_F, image=r)
    d.pack()
    B = Button(w5_F, text='Try again', font=('Angsana New', 25), bg="#FFC796", command=try5)
    B.pack(pady=20)
    B2 = Button(w5_F, text='Next', font=('Angsana New', 25), bg="#FFC796", command=next5)
    B2.pack(pady=20)
    w5_F.pack()
    w5.mainloop()

def wrong6():
    def try6():
        w1.destroy()
        test6()
    def next6():
        w1.destroy()
        test7()
    w1 = Tk()
    w1.title('Ring of fire')
    w1.geometry('750x650')
    w1.configure(background='red')
    w1_F = Frame(w1, width=600, height=600)
    w1_F.configure(background='red')
    Ring_Lb = Label(w1_F, text='ดูเหมือนว่าคุณจะตอบผิดนะ ลองใหม่อีกครั้งหรือไม่', font=('Angsana New', 30),bg='pink', width=50,height=2)
    Ring_Lb.pack()
    r = PhotoImage(file="w1.png")
    d = Label(w1_F, image=r)
    d.pack()
    B = Button(w1_F, text='Try again', font=('Angsana New', 25), bg="#FFC796", command=try6)
    B.pack(pady=20)
    B2 = Button(w1_F, text='Next', font=('Angsana New', 25), bg="#FFC796", command=next6)
    B2.pack(pady=20)
    w1_F.pack()
    w1.mainloop()
def wrong7():
    def try7():
        w1.destroy()
        test7()
    def next7():
        w1.destroy()
        test8()
    w1 = Tk()
    w1.title('Ring of fire')
    w1.geometry('750x650')
    w1.configure(background='red')
    w1_F = Frame(w1, width=600, height=600)
    w1_F.configure(background='red')
    Ring_Lb = Label(w1_F, text='ดูเหมือนว่าคุณจะตอบผิดนะ ลองใหม่อีกครั้งหรือไม่', font=('Angsana New', 30),bg='pink', width=50,height=2)
    Ring_Lb.pack()
    r = PhotoImage(file="w1.png")
    d = Label(w1_F, image=r)
    d.pack()
    B = Button(w1_F, text='Try again', font=('Angsana New', 25), bg="#FFC796", command=try7)
    B.pack(pady=20)
    B2 = Button(w1_F, text='Next', font=('Angsana New', 25), bg="#FFC796", command=next7)
    B2.pack(pady=20)
    w1_F.pack()
    w1.mainloop()
def wrong8():
    def try8():
        w1.destroy()
        test8()
    def the_end():
        w1.destroy()
        Main1()
    def ask():
        w1.destroy()
        answer()
    w1 = Tk()
    w1.title('Ring of fire')
    w1.geometry('750x650')
    w1.configure(background='red')
    w1_F = Frame(w1, width=600, height=600)
    w1_F.configure(background='red')
    Ring_Lb = Label(w1_F, text='ดูเหมือนว่าคุณจะตอบผิดนะ ลองใหม่อีกครั้งหรือไม่', font=('Angsana New', 30),bg='pink', width=50,height=2)
    Ring_Lb.pack()
    r = PhotoImage(file="w1.png")
    d = Label(w1_F, image=r)
    d.pack()
    B = Button(w1_F, text='Try again', font=('Angsana New', 25), bg="#FFC796", command=try8)
    B.pack(pady=20)
    B2 = Button(w1_F, text='Menu', font=('Angsana New', 25), bg="#FFC796", command=the_end)
    B2.pack(pady=20)
    B3 = Button(w1_F, text='Answer', font=('Angsana New', 25), bg="#FFC796", command=ask)
    B3.pack(pady=20)
    w1_F.pack()
    w1.mainloop()

def Organizer():
    def Menu():
        o.destroy()
        Main1()
    o=Tk()
    o.title('Ring of fire')
    o.geometry('750x550')
    o.configure(background='#FFDD8F')
    o_F=Frame(o,width=600,height=600)
    o_F.configure(background='#FFDD8F')
    r=PhotoImage(file="o.png")
    d=Label(o_F,image=r)
    d.pack()
    B=Button(o_F, text='Menu', font=('', 25), bg="#FFC796", command=Menu)
    B.pack(pady=40,side=RIGHT)
    o_F.pack()
    o.mainloop()

def lesson1():
    def Skip():
        o.destroy()
        lesson2()
    o=Tk()
    o.title('Ring of fire')
    o.geometry('750x750')
    o.configure(background='#FFDD8F')
    o_F=Frame(o,width=600,height=600)
    o_F.configure(background='#FFDD8F')
    r=PhotoImage(file="1.png")
    d=Label(o_F,image=r)
    d.pack()
    B=Button(o_F, text='Next', font=('', 25), bg="#FFC796", command=Skip)
    B.pack(pady=40,side=RIGHT)
    o_F.pack()
    o.mainloop()

def lesson2():
    def skip2():
        o.destroy()
        lesson3()
    o=Tk()
    o.title('Ring of fire')
    o.geometry('750x750')
    o.configure(background='#FFDD8F')
    o_F=Frame(o,width=600,height=600)
    o_F.configure(background='#FFDD8F')
    r=PhotoImage(file="2.png")
    d=Label(o_F,image=r)
    d.pack()
    B=Button(o_F, text='Next', font=('', 25), bg="#FFC796", command=skip2)
    B.pack(pady=40,side=RIGHT)
    o_F.pack()
    o.mainloop()

def lesson3():
    def skip3():
        o.destroy()
        lesson4()
    o=Tk()
    o.title('Ring of fire')
    o.geometry('750x750')
    o.configure(background='#FFDD8F')
    o_F=Frame(o,width=600,height=600)
    o_F.configure(background='#FFDD8F')
    r=PhotoImage(file="3.png")
    d=Label(o_F,image=r)
    d.pack()
    B=Button(o_F, text='Next', font=('', 25), bg="#FFC796", command=skip3)
    B.pack(pady=40,side=RIGHT)
    o_F.pack()
    o.mainloop()

def lesson4():
    def skip4():
        o.destroy()
        lesson5()
    o=Tk()
    o.title('Ring of fire')
    o.geometry('750x750')
    o.configure(background='#FFDD8F')
    o_F=Frame(o,width=600,height=600)
    o_F.configure(background='#FFDD8F')
    r=PhotoImage(file="4.png")
    d=Label(o_F,image=r)
    d.pack()
    B=Button(o_F, text='Next', font=('', 25), bg="#FFC796", command=skip4)
    B.pack(pady=40,side=RIGHT)
    o_F.pack()
    o.mainloop()

def lesson5():
    def skip5():
        o.destroy()
        lesson6()
    o=Tk()
    o.title('Ring of fire')
    o.geometry('750x750')
    o.configure(background='#FFDD8F')
    o_F=Frame(o,width=600,height=600)
    o_F.configure(background='#FFDD8F')
    r=PhotoImage(file="5.png")
    d=Label(o_F,image=r)
    d.pack()
    B=Button(o_F, text='Next', font=('', 25), bg="#FFC796", command=skip5)
    B.pack(pady=40,side=RIGHT)
    o_F.pack()
    o.mainloop()

def lesson6():
    def skip6():
        o.destroy()
        lesson7()
    o=Tk()
    o.title('Ring of fire')
    o.geometry('750x750')
    o.configure(background='#FFDD8F')
    o_F=Frame(o,width=600,height=600)
    o_F.configure(background='#FFDD8F')
    r=PhotoImage(file="6.png")
    d=Label(o_F,image=r)
    d.pack()
    B=Button(o_F, text='Next', font=('', 25), bg="#FFC796", command=skip6)
    B.pack(pady=40,side=RIGHT)
    o_F.pack()
    o.mainloop()

def lesson7():
    def skip7():
        o.destroy()
        lesson8()
    o=Tk()
    o.title('Ring of fire')
    o.geometry('750x750')
    o.configure(background='#FFDD8F')
    o_F=Frame(o,width=600,height=600)
    o_F.configure(background='#FFDD8F')
    r=PhotoImage(file="7.png")
    d=Label(o_F,image=r)
    d.pack()
    B=Button(o_F, text='Next', font=('', 25), bg="#FFC796", command=skip7)
    B.pack(pady=40,side=RIGHT)
    o_F.pack()
    o.mainloop()

def lesson8():
    def skip8():
        o.destroy()
        lesson9()
    o=Tk()
    o.title('Ring of fire')
    o.geometry('750x750')
    o.configure(background='#FFDD8F')
    o_F=Frame(o,width=600,height=600)
    o_F.configure(background='#FFDD8F')
    r=PhotoImage(file="8.png")
    d=Label(o_F,image=r)
    d.pack()
    B=Button(o_F, text='Next', font=('', 25), bg="#FFC796", command=skip8)
    B.pack(pady=40,side=RIGHT)
    o_F.pack()
    o.mainloop()

def lesson9():
    def skip9():
        o.destroy()
        lesson10()
    o=Tk()
    o.title('Ring of fire')
    o.geometry('750x750')
    o.configure(background='#FFDD8F')
    o_F=Frame(o,width=600,height=600)
    o_F.configure(background='#FFDD8F')
    r=PhotoImage(file="9.png")
    d=Label(o_F,image=r)
    d.pack()
    B=Button(o_F, text='Next', font=('', 25), bg="#FFC796", command=skip9)
    B.pack(pady=40,side=RIGHT)
    o_F.pack()
    o.mainloop()

def lesson10():
    def skip10():
        o.destroy()
        test1()
    def exit():
        o.destroy()
    o=Tk()
    o.title('Ring of fire')
    o.geometry('750x750')
    o.configure(background='#FFDD8F')
    o_F=Frame(o,width=600,height=600)
    o_F.configure(background='#FFDD8F')
    r=PhotoImage(file="10.png")
    d=Label(o_F,image=r)
    d.pack()
    B=Button(o_F, text='Take a test', font=('', 25), bg="#FFC796", command=skip10)
    B.pack(pady=40,side=RIGHT)
    B1 = Button(o_F, text='Exit', font=('', 25), bg="#FFC796", command=exit)
    B1.pack(pady=40, side=LEFT)
    o_F.pack()
    o.mainloop()

def answer():
    def m1():
        o.destroy()
        Main1()
    def close():
        o.destroy()
    o = Tk()
    o.title('Ring of fire')
    o.geometry('750x550')
    o.configure(background='#FFDD8F')
    o_F = Frame(o, width=600, height=600)
    o_F.configure(background='#FFDD8F')
    r = PhotoImage(file="เฉลย.png")
    d = Label(o_F, image=r)
    d.pack()
    B = Button(o_F, text='Menu', font=('', 25), bg="#FFC796", command=m1)
    B.pack(pady=40, side=LEFT)
    B1 = Button(o_F, text='Exit', font=('', 25), bg="#FFC796", command=close)
    B1.pack(pady=40, side=RIGHT)
    o_F.pack()
    o.mainloop()

def Main1():
    def go():
        Main_window.destroy()
        Organizer()
    def gt():
        Main_window.destroy()
        test1()
    def gotolearn():
        Main_window.destroy()
        lesson1()
    def away():
        Main_window.destroy()
    Main_window=Tk()
    Main_window.geometry('750x550')
    Main_window.title('Ring of fire')
    Main_window.configure(background='#FFDD8F')
    Ring_Lb = Label(Main_window, text='Ring of fire', font=('',30),fg='#FF7700',bg="#FFC796",width=33)
    Ring_Lb.pack()
    Button(Main_window,text='Lesson', font=('',25),bg="#FFC796",command=gotolearn).pack(pady=20)
    Button(Main_window,text='Test', font=('',25),bg="#FFC796",command=gt).pack(pady=20)
    Button(Main_window,text='Organizer', font=('',25),bg="#FFC796",command=go).pack(pady=20)
    Button(Main_window,text='Exit', font=('',25),bg="#FFC796",command=away).pack(pady=20)
    Main_window.mainloop()
Main1()